# Generated by Django 4.1 on 2022-12-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0002_remove_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="userage",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
