# Generated by Django 4.1 on 2022-12-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0004_contact_test_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
