# Generated by Django 4.1 on 2022-12-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0005_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=32)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("publish", models.CharField(max_length=32)),
                ("pub_date", models.DateField()),
            ],
        ),
    ]
